<!--<template>
  <div class="modal">
    <form v-on:submit.prevent class="modal-conteudo animate width-25">
    <span class="fechar" v-on:click="$emit('fechar')">&times;</span>
        <div class="prof">
            <img src="../../images/porcoprofessor.png">
            <p>Área do Professor</p>
                <div class="quantia">
                    <big>R$</big>
                    <input
                    placeholder="0,00" 
                    type="number"
                    min="1"
                    max="1000000"
                    step="any"
                    class="campos"
                    v-model="registro.quantia"
                    required
                    />
                </div>
        </div>
        <div class="aluno">
            <img src="../../images/porcoprofessor.png">
            <p>Área do Professor</p>
                <div class="quantia">
                    <big>R$</big>
                    <input
                    placeholder="0,00" 
                    type="number"
                    min="1"
                    max="1000000"
                    step="any"
                    class="campos"
                    v-model="registro.quantia"
                    required
                    />
                </div>
        </div>
    </form>
  </div>

</template> -->